swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Phone Catalog Service
host: localhost:8080
# Describe your paths here
paths:
  /phonecatalog/:
    get:
      tags:
       - getPhoneCatalog
      summary: Find all Phones in Catalog
      description: |
        Find all Phones in Catalog.
      operationId: getPhoneCatalog
      produces:
        - application/json
      responses:
        # Response code
        '200':
          description: Successful response
          schema:
            title: ArrayOfPhone
            type: array
            items:
              $ref: '#/definitions/Phone'
        '501':
          description: Not found
          schema:
            $ref: '#/definitions/InternalErrorResponse'
definitions:
  Phone:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      price:
        type: number
        format: double
      description:
        type: string
      imagePath:
        type: string
  InternalErrorResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
