springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  contextPath:
  port: 8080
spring:
  jackson:
    date-format: mobile.catalog.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false