/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package mobile.catalog.api;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import mobile.catalog.model.InternalErrorResponse;
import mobile.catalog.model.Phone;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-07T08:38:48.647Z")

@Api(value = "phonecatalog", description = "the phonecatalog API")
public interface PhonecatalogApi {

    @ApiOperation(value = "Find all Phones in Catalog", nickname = "getPhoneCatalog", notes = "Find all Phones in Catalog. ", response = Phone.class, responseContainer = "List", tags={ "getPhoneCatalog", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Phone.class, responseContainer = "List"),
        @ApiResponse(code = 501, message = "Not found", response = InternalErrorResponse.class) })
    @RequestMapping(value = "/phonecatalog/",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Phone>> getPhoneCatalog();

}
